---
- hosts: all
  become: true
  remote_user: ubuntu
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools','python-pip']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Creates directory
      file:
        path: /home/ubuntu/.aws
        state: directory
    - name : Copy AWS credential file
      copy :
        src : /home/pi/.aws/credentials 
        dest : /home/ubuntu/.aws/credentials.aws
        owner : ubuntu
        group: ubuntu
        mode : '0400'


    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create and start container
      docker_container:
        name: docker
        image: alexyop/testaws:0.0.3
        ports:
            - "8888:8888"
        volumes:
            - /home/ubuntu/.aws/:/credentials/:ro
        #command: "{{ default_container_command }}"
        state: started
